<a href="https://colab.research.google.com/github/Amanya-Brian/mlzoomcamp/blob/main/numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Creating Arrays

In [ ]:
a = np.full(10,3)
a

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

## Converting a list to an array

In [ ]:
my_list = [12,13,14,15]
my_array = np.array(my_list)
my_list
my_array

array([12, 13, 14, 15])

# Generating a range of numbers

In [ ]:
b = np.arange(0,10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Creating arrays with linear spacing

In [ ]:
c = np.linspace(0,90,10)
c

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

# Creating multidimensional arrays

In [ ]:
d = np.full((5,2),3)
d

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

In [ ]:
d[2,1] = 9
d

array([[3, 3],
       [3, 3],
       [3, 9],
       [3, 3],
       [3, 3]])

# Generating random arrays

In [ ]:
np.random.seed(10)
e = np.random.rand(5)
e

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701])

# Array Multiplications

In [ ]:
u = np.array([1,2,3,4])
v = np.array([2,0,0,4])

In [ ]:


def vector_vector_mult(u1,v1):

    assert u1.shape[0] == v1.shape[0]

    result = 0.0

    for i in range(u1.shape[0]):
        result = result + u1[i] * v1[i]

    return result

u

array([1, 2, 3, 4])

In [ ]:
print(u * v)
print(vector_vector_mult(u,v))
print("Here we go")
u.dot(v)

[ 2  0  0 16]
18.0
Here we go


18

# Matrix Vector multiplication

In [ ]:
U = np.array([[2,4,3,1],[2,0,3,1],[0,4,2,3]])
U

array([[2, 4, 3, 1],
       [2, 0, 3, 1],
       [0, 4, 2, 3]])

In [ ]:
def matrix_vector_mult(U,v):
    assert U.shape[1] == v.shape[0]

    mv_result = np.zeros(U.shape[0])

    for i in range(U.shape[0]):
        mv_result[i] = vector_vector_mult(U[i],v)

    return mv_result

In [ ]:
print(U.dot(v))
print(matrix_vector_mult(U,v))

[ 8  8 12]
[ 8.  8. 12.]


# Matrix Matrix Multiplication

In [ ]:
V = np.array([[1,2,3],[2,4,3],[4,1,3],[3,2,1]])
print(V.shape)
print(U.shape)

(4, 3)
(3, 4)


In [ ]:
def matrix_matrix_mult(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:,i]
        Uvi = matrix_vector_mult(U, vi)
        result[:, i] = Uvi

    return result

In [ ]:
print(matrix_matrix_mult(U, V))
U.dot(V)

[[25. 25. 28.]
 [17.  9. 16.]
 [25. 24. 21.]]


array([[25, 25, 28],
       [17,  9, 16],
       [25, 24, 21]])

# Identity Matrix

In [ ]:
d = np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Inverse

In [ ]:
Vs = V[[0,1,2]]
Vs

array([[1, 2, 3],
       [2, 4, 3],
       [4, 1, 3]])

In [ ]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[-0.42857143,  0.14285714,  0.28571429],
       [-0.28571429,  0.42857143, -0.14285714],
       [ 0.66666667, -0.33333333,  0.        ]])

In [ ]:
# to get the identity matrix
Vs_inv.dot(Vs)

array([[ 1.00000000e+00, -1.11022302e-16, -1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])